-- ============================================================
-- GOOGLE SHEETS LEAD SYNC WEBHOOK (INSTRUCTIONS)
-- ============================================================

-- This migration doesn't run code directly, but serves as a reminder 
-- of the table structure to ensure your Google Sheet matches.

-- Field Mapping for Google Sheet:
/*
  1. Date       (Generated by Script)
  2. Name       (leads.name)
  3. Email      (leads.email)
  4. Phone      (leads.phone)
  5. Firm       (leads.firm_name)
  6. Service    (leads.service or leads.industry)
  7. Budget     (leads.budget)
  8. Source     (leads.source)
  9. Message    (leads.message or leads.notes)
*/

-- To verify your leads table has these columns, you can run:
/*
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'leads';
*/

-- To set up the Webhook in Supabase:
-- 1. Go to Database -> Webhooks.
-- 2. Create 'sync_to_gsheets' for table 'leads' on 'Insert'.
-- 3. Use 'POST' and your Google Script URL.
